
default: &default
  adapter: postgresql
  encoding: unicode
  password: 1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Avispa_development
test:
  <<: *default
  database: Avispa_test
production:
  <<: *default
  database: Avispa_production
  username: Avispa
  password: <%= ENV['AVISPA_DATABASE_PASSWORD'] %>
